version: '3.0'
services:
  db:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '8hP42R0AAXIgnNZxO'
      MYSQL_ROOT_PASSWORD: '8hP42R0AAXIgnNZxO'
    expose:
      - "3306"
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local